
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'A ARTICLE BAG DIRECTION DOOR DRAGON EAST ENTER GO GRAB HOUSE ITEM KILL NORTH NOUN POTION PRINCESS SAVE SOUTH SWING SWORD THE VERB WEST WORD\n\tmoveCommand : VERB DIRECTION\n\t\n\tgrabCommand : VERB ARTICLE ITEM\n\t\n\tdropCommand : VERB NOUN\n\t'
    
_lr_action_items = {'VERB':([0,],[2,]),'$end':([1,3,],[0,-1,]),'DIRECTION':([2,],[3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'moveCommand':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> moveCommand","S'",1,None,None,None),
  ('moveCommand -> VERB DIRECTION','moveCommand',2,'p_move_command','ParserTest.py',79),
  ('grabCommand -> VERB ARTICLE ITEM','grabCommand',3,'p_grab_command','ParserTest.py',88),
  ('dropCommand -> VERB NOUN','dropCommand',2,'p_drop_command','ParserTest.py',97),
]
